// src/components/screens/DonationHistory.jsx
//
// Shows the logged-in donor's REAL donation history from donation-service
// (GET /api/donations/mine), and lets them log a new donation (POST
// /api/donations) - each one gets a real certificate number generated by
// the backend (see DonationService.create() in donation-service).
import { useEffect, useState } from "react";
import { C } from "../../tokens";
import { Card, Field } from "../shared/UI";
import { listMyDonations, createDonation, getToken } from "../../api";

const EMPTY_FORM = { bloodGroup: "O+", donationDate: "", location: "" };
const bloodGroups = ["A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"];

export default function DonationHistory() {
  const token = getToken();
  const [donations, setDonations] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const [form, setForm] = useState(EMPTY_FORM);
  const [formError, setFormError] = useState("");
  const [submitting, setSubmitting] = useState(false);

  function load() {
    if (!token) {
      setError("You're not signed in. Please log in again.");
      setLoading(false);
      return;
    }
    listMyDonations(token)
      .then(data => setDonations(data))
      .catch(err => setError(err.message || "Could not load donation history"))
      .finally(() => setLoading(false));
  }

  useEffect(load, [token]);

  async function submit() {
    if (!form.donationDate) return setFormError("Donation date is required");
    if (!form.location.trim()) return setFormError("Location is required");
    setFormError("");
    setSubmitting(true);
    try {
      const created = await createDonation(token, form);
      setDonations(list => [created, ...list]);
      setForm(EMPTY_FORM);
    } catch (err) {
      setFormError(err.message || "Could not log donation");
    } finally {
      setSubmitting(false);
    }
  }

  const totalDonations = donations.length;
  // Each whole-blood donation is roughly 450ml - a reasonable estimate
  // since donation-service doesn't track volume per donation.
  const totalLitres = ((totalDonations * 450) / 1000).toFixed(1);
  const livesImpacted = totalDonations * 3; // each donation can help up to 3 people

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      <div style={{ display: "flex", gap: 11 }}>
        {[
          [String(totalDonations), "donations", C.red700],
          [`${totalLitres} L`, "blood given (est.)", C.blue],
          [`~${livesImpacted}`, "lives impacted (est.)", C.green],
        ].map(([v, l, col]) => (
          <div key={l} style={{ flex: 1, background: C.white, borderRadius: 11, border: `1px solid ${C.border}`, padding: "14px 16px", boxShadow: "0 1px 3px rgba(17,21,39,0.05)" }}>
            <div style={{ width: 32, height: 3, background: col, borderRadius: 2, marginBottom: 9 }} />
            <div style={{ fontSize: 22, fontWeight: 700, color: col, letterSpacing: "-0.5px" }}>{v}</div>
            <div style={{ fontSize: 10.5, color: C.gray, marginTop: 4 }}>{l}</div>
          </div>
        ))}
      </div>

      <Card style={{ padding: "18px 20px" }}>
        <div style={{ fontSize: 13, fontWeight: 700, color: C.navy, marginBottom: 12 }}>Log a new donation</div>
        <div style={{ display: "flex", gap: 12, alignItems: "flex-end", flexWrap: "wrap" }}>
          <div>
            <label style={{ display: "block", fontSize: 11, fontWeight: 600, color: C.slate, marginBottom: 4 }}>Blood group</label>
            <select value={form.bloodGroup} onChange={e => setForm(f => ({ ...f, bloodGroup: e.target.value }))} style={{ height: 38, borderRadius: 7, border: `1px solid ${C.border}`, padding: "0 10px", fontSize: 12.5 }}>
              {bloodGroups.map(g => <option key={g} value={g}>{g}</option>)}
            </select>
          </div>
          <div style={{ width: 160 }}>
            <Field label="Donation date" type="date" value={form.donationDate} onChange={e => setForm(f => ({ ...f, donationDate: e.target.value }))} required />
          </div>
          <div style={{ flex: 1, minWidth: 200 }}>
            <Field label="Location" placeholder="City Hospital, Coimbatore" value={form.location} onChange={e => setForm(f => ({ ...f, location: e.target.value }))} required />
          </div>
          <button onClick={submit} disabled={submitting} style={{ height: 38, padding: "0 18px", background: C.red700, color: C.white, border: "none", borderRadius: 8, fontSize: 12.5, fontWeight: 700, cursor: submitting ? "default" : "pointer", opacity: submitting ? 0.7 : 1 }}>
            {submitting ? "Saving…" : "Log donation"}
          </button>
        </div>
        {formError && <div style={{ fontSize: 11, color: C.red700, marginTop: 8 }}>{formError}</div>}
      </Card>

      <Card style={{ overflow: "hidden" }}>
        <div style={{ height: 3, background: C.red700 }} />
        <div style={{ padding: "16px 18px" }}>
          {error && <div style={{ fontSize: 11.5, color: C.red700, background: C.red50, borderRadius: 7, padding: "8px 12px", marginBottom: 10 }}>{error}</div>}
          {loading ? (
            <div style={{ textAlign: "center", padding: "28px 0", color: C.gray, fontSize: 13 }}>Loading…</div>
          ) : donations.length === 0 ? (
            <div style={{ textAlign: "center", padding: "28px 0", color: C.gray, fontSize: 13 }}>No donations logged yet.</div>
          ) : (
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 12 }}>
              <thead>
                <tr>
                  {["Date", "Location", "Group", "Certificate"].map(h => (
                    <th key={h} style={{ textAlign: "left", padding: "8px 12px", fontSize: 10.5, fontWeight: 700, color: C.gray, background: C.warmgray, borderBottom: `1px solid ${C.border}`, textTransform: "uppercase", letterSpacing: "0.05em" }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {donations.map((d, i) => (
                  <tr key={d.id} style={{ borderBottom: `1px solid ${C.border}66`, background: i % 2 === 0 ? "#FAFBFC" : C.white }}>
                    <td style={{ padding: "10px 12px", color: C.navy, fontWeight: 500, whiteSpace: "nowrap" }}>{d.donationDate}</td>
                    <td style={{ padding: "10px 12px", color: C.slate }}>{d.location}</td>
                    <td style={{ padding: "10px 12px" }}><span style={{ fontSize: 12, fontWeight: 700, color: C.red700 }}>{d.bloodGroup}</span></td>
                    <td style={{ padding: "10px 12px", color: C.slate }}>{d.certificateId}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </Card>
    </div>
  );
}
